### ISSUE TITLE
Alias_attribute required

### ISSUE THREAD

**Issue by iamwilhelm** [pietern/googlecontacts#2]
It seems like googlecontacts is a standalone lib, but it relies on alias_attribute, which is contained in rails, so you'd need to specify active_record (I think) as a dependency.

Wil

**Comment by pietern** [comment]
Yes, it depends on Active Support. See:
https://github.com/pietern/googlecontacts/blob/master/lib/google_contacts.rb#L3

**Comment by pietern** [comment]
Quick followup:
You're right, it doesn't work with Active Support 3.0. #alias_attribute was moved to Active Model in 3.0. I'll try and see if I can hack a way around it.

**Comment by pietern** [comment]
Just pushed 0.1.8 that passes all specs against Active Support 3.0.

**Comment by iamwilhelm** [comment]
Cool, thanks for the followup, and thinking to test it with active_support 3.0 I had failed to mention I was using rails3. Anyway, keep up the good work. :)

Wil
